### ISSUE TITLE
Morning session: Peer-to-peer code review 02/09

### ISSUE THREAD

**Issue by jorgeabrahan** [Uthmanbello/capstone2#28]
Great Job so far!
You and your partner have really good progress.
### Highlights
☑️ Clean and neat code
☑️ ES6 syntax
☑️ Use of promises
☑️ Retrieve data from the API
☑️ Nice GitFlow

However, there are still a few things that you can work on:
- On the View.js file when you display the data from the array, instead of appending directly to the container, consider using a document fragment to boost the performance of your website.
https://github.com/Uthmanbello/capstone2/blob/a72cfcecdc0ecde612dfe893012d2c1f332a8718/src/modules/views.js#L19

**Comment by Uthmanbello** [comment]
Ok. Thanks a lot 👍
